# config.py
# CONFIGURACAO CANONICA - NAO MEXER SEM MOTIVO

BASE = r"C:\IA_AUTOMACAO"

ENTIDADE_ATIVA = "Empresa_A"

STORAGE = rf"{BASE}\STORAGE"
EMPRESA_PATH = rf"{STORAGE}\{ENTIDADE_ATIVA}"

ENTRADA = rf"{EMPRESA_PATH}\ENTRADA"
PROCESSADOS = rf"{EMPRESA_PATH}\PROCESSADOS"
RESULTADOS = rf"{EMPRESA_PATH}\RESULTADOS"
ERRO = rf"{EMPRESA_PATH}\ERRO"
REPROCESSADOS = rf"{EMPRESA_PATH}\REPROCESSADOS"
SAIDA = rf"{EMPRESA_PATH}\SAIDA"

AUDITORIA = rf"{STORAGE}\AUDITORIA"
EVENTOS_CSV = rf"{AUDITORIA}\EVENTOS_EMPRESA.csv"